StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{657F5D99D979EC60}" {
   Id "#AR-Item_wog_ANPRC68_multichannel_Name"
   Target_en_us "ANPRC68 Leader radio"
   Target_fr_fr "Target De De"
   Target_it_it "ANPRC68 Leader radio"
   Target_de_de "ANPRC68 Leader radio"
   Target_es_es "ANPRC68 Leader radio"
   Target_cs_cz "ANPRC68 Velitelská radiostanice"
   Target_pl_pl "ANPRC68 Leader radio"
   Target_ru_ru "ANPRC68 Рация командира"
   Target_ja_jp "ANPRC68 Leader radio"
   Target_ko_kr "ANPRC68 Leader radio"
   Target_pt_br "ANPRC68 Leader radio"
   Target_zh_cn "ANPRC68 Leader radio"
   Target_uk_ua "ANPRC68 Leader radio"
   Modified 1702846906
   Author "dockez"
   LastChanged "dockez"
  }
  CustomStringTableItem "{657F37627FC2BE9E}" {
   Id "#AR-Item_wog_ANPRC68_singlechannel_Name"
   Target_en_us "ANPRC68 Rifleman radio"
   Target_fr_fr "ANPRC68 Rifleman radio"
   Target_it_it "ANPRC68 Rifleman radio"
   Target_de_de "ANPRC68 Rifleman radio"
   Target_es_es "ANPRC68 Rifleman radio"
   Target_cs_cz "ANPRC68 Střelecké radiostanice"
   Target_pl_pl "ANPRC68 Rifleman radio"
   Target_ru_ru "ANPRC68 Рация пехотинца"
   Target_ja_jp "ANPRC68 Rifleman radio"
   Target_ko_kr "ANPRC68 Rifleman radio"
   Target_pt_br "ANPRC68 Rifleman radio"
   Target_zh_cn "ANPRC68 Rifleman radio"
   Target_uk_ua "ANPRC68 Rifleman radio"
   Terminology NONE
   Modified 1702846882
   Author "dockez"
   LastChanged "dockez"
  }
 }
}